name: Workflow 1 - Dependent Jobs

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start build
        run: echo "Building application..."

      - name: Simulate build work
        run: sleep 3

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Start tests
        run: echo "Running tests..."

      - name: Simulate test work
        run: sleep 3

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Start deployment
        run: echo "Deploying application..."

      - name: Simulate deploy work
        run: sleep 3
